# Generated by Django 4.2.27 on 2026-02-01 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "culprit",
                    models.CharField(
                        blank=True,
                        help_text="The function/module where the error originated",
                        max_length=500,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="error",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                            ("muted", "Muted"),
                        ],
                        default="unresolved",
                        max_length=20,
                    ),
                ),
                ("exception_type", models.CharField(db_index=True, max_length=255)),
                ("exception_value", models.TextField(blank=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("event_count", models.PositiveIntegerField(default=1)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("affected_users", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "is_regression",
                    models.BooleanField(
                        default=False, help_text="Was this error previously resolved?"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_error_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Group",
                "verbose_name_plural": "Error Groups",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exception_type", models.CharField(db_index=True, max_length=255)),
                ("exception_value", models.TextField()),
                ("exception_module", models.CharField(blank=True, max_length=255)),
                (
                    "traceback_text",
                    models.TextField(blank=True, help_text="Human-readable traceback"),
                ),
                (
                    "traceback_frames",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured stack frames as JSON",
                    ),
                ),
                (
                    "culprit",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("filename", models.CharField(blank=True, max_length=500)),
                ("function", models.CharField(blank=True, max_length=255)),
                ("lineno", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("request_method", models.CharField(blank=True, max_length=10)),
                (
                    "request_path",
                    models.CharField(blank=True, db_index=True, max_length=2000),
                ),
                ("request_url", models.URLField(blank=True, max_length=2000)),
                (
                    "request_query",
                    models.TextField(blank=True, help_text="Query string parameters"),
                ),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                (
                    "request_body",
                    models.TextField(blank=True, help_text="Truncated request body"),
                ),
                (
                    "user_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("server_name", models.CharField(blank=True, max_length=255)),
                (
                    "environment",
                    models.CharField(blank=True, default="production", max_length=50),
                ),
                (
                    "release",
                    models.CharField(
                        blank=True,
                        help_text="Application version/release",
                        max_length=100,
                    ),
                ),
                ("django_version", models.CharField(blank=True, max_length=20)),
                ("python_version", models.CharField(blank=True, max_length=20)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="error",
                        max_length=20,
                    ),
                ),
                ("logger_name", models.CharField(blank=True, max_length=255)),
                (
                    "extra_context",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context data"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=dict, help_text="Searchable tags"
                    ),
                ),
                (
                    "breadcrumbs",
                    models.JSONField(
                        blank=True, default=list, help_text="Event breadcrumbs/trail"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("sql_query_count", models.PositiveIntegerField(blank=True, null=True)),
                ("sql_query_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="observability.errorgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("server_name", models.CharField(blank=True, max_length=255)),
                ("requests_per_minute", models.PositiveIntegerField(default=0)),
                ("errors_per_minute", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0)),
                ("p95_response_time_ms", models.FloatField(default=0)),
                (
                    "db_connections_active",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "db_connections_available",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("memory_used_mb", models.FloatField(blank=True, null=True)),
                ("memory_available_mb", models.FloatField(blank=True, null=True)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("active_users", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "System Metric",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="observabili_timesta_39690b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("daily", "Daily")],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField(db_index=True)),
                (
                    "path_pattern",
                    models.CharField(
                        db_index=True,
                        help_text="URL pattern (normalized)",
                        max_length=500,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=10)),
                ("view_name", models.CharField(blank=True, max_length=255)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("duration_avg", models.FloatField(default=0)),
                ("duration_min", models.FloatField(default=0)),
                ("duration_max", models.FloatField(default=0)),
                (
                    "duration_p50",
                    models.FloatField(default=0, help_text="50th percentile (median)"),
                ),
                (
                    "duration_p95",
                    models.FloatField(default=0, help_text="95th percentile"),
                ),
                (
                    "duration_p99",
                    models.FloatField(default=0, help_text="99th percentile"),
                ),
                ("sql_count_avg", models.FloatField(default=0)),
                ("sql_time_avg", models.FloatField(default=0)),
                (
                    "error_rate",
                    models.FloatField(
                        default=0, help_text="Percentage of requests that errored"
                    ),
                ),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Performance Metric",
                "verbose_name_plural": "Performance Metrics",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["period", "-period_start"],
                        name="observabili_period_c3f863_idx",
                    ),
                    models.Index(
                        fields=["path_pattern", "-period_start"],
                        name="observabili_path_pa_023034_idx",
                    ),
                    models.Index(
                        fields=["-error_rate"], name="observabili_error_r_d3a1d3_idx"
                    ),
                ],
                "unique_together": {
                    ("period", "period_start", "path_pattern", "method")
                },
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("logger_name", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                ("filename", models.CharField(blank=True, max_length=500)),
                ("function", models.CharField(blank=True, max_length=255)),
                ("lineno", models.PositiveIntegerField(blank=True, null=True)),
                ("module", models.CharField(blank=True, max_length=255)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "user_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["level", "-timestamp"],
                        name="observabili_level_e40705_idx",
                    ),
                    models.Index(
                        fields=["logger_name", "-timestamp"],
                        name="observabili_logger__e705f5_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="observabili_request_b987be_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=2000)),
                ("full_url", models.URLField(blank=True, max_length=2000)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                (
                    "request_body",
                    models.TextField(blank=True, help_text="Truncated request body"),
                ),
                ("request_content_type", models.CharField(blank=True, max_length=100)),
                ("status_code", models.PositiveSmallIntegerField(db_index=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                (
                    "response_body_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Response size in bytes", null=True
                    ),
                ),
                (
                    "user_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                (
                    "user_ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "company_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "duration_ms",
                    models.FloatField(
                        db_index=True,
                        help_text="Total request duration in milliseconds",
                    ),
                ),
                ("time_to_first_byte_ms", models.FloatField(blank=True, null=True)),
                ("sql_query_count", models.PositiveIntegerField(default=0)),
                ("sql_query_time_ms", models.FloatField(default=0)),
                (
                    "sql_queries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of SQL queries (if profiling enabled)",
                    ),
                ),
                (
                    "view_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("view_class", models.CharField(blank=True, max_length=255)),
                ("server_name", models.CharField(blank=True, max_length=255)),
                (
                    "environment",
                    models.CharField(blank=True, default="production", max_length=50),
                ),
                ("has_error", models.BooleanField(db_index=True, default=False)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "error_log",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_log",
                        to="observability.errorlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="observabili_timesta_2440d9_idx"
                    ),
                    models.Index(
                        fields=["status_code", "-timestamp"],
                        name="observabili_status__59771d_idx",
                    ),
                    models.Index(
                        fields=["path", "-timestamp"],
                        name="observabili_path_c46bea_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-timestamp"],
                        name="observabili_user_id_8a9d39_idx",
                    ),
                    models.Index(
                        fields=["has_error", "-timestamp"],
                        name="observabili_has_err_d49952_idx",
                    ),
                    models.Index(
                        fields=["-duration_ms"], name="observabili_duratio_3eef0d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["-timestamp"], name="observabili_timesta_e50424_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["exception_type", "-timestamp"],
                name="observabili_excepti_b28baf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["level", "-timestamp"], name="observabili_level_b559a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["request_path", "-timestamp"],
                name="observabili_request_f3ce4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["user_id", "-timestamp"], name="observabili_user_id_d7aad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorgroup",
            index=models.Index(
                fields=["status", "-last_seen"], name="observabili_status_13d0ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorgroup",
            index=models.Index(
                fields=["exception_type", "-last_seen"],
                name="observabili_excepti_cbbebd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorgroup",
            index=models.Index(
                fields=["-event_count"], name="observabili_event_c_3199d6_idx"
            ),
        ),
    ]
