# Generated by Django 4.2.23 on 2025-12-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="badge_id",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="ifsc_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="IFSC Code"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Single"),
                    ("M", "Married"),
                    ("D", "Divorced"),
                    ("W", "Widowed"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permanent_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="pf_enabled",
            field=models.BooleanField(default=False, verbose_name="Provident Fund"),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.CharField(blank=True, default="General", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="uan",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="UAN"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("FT", "Full Time"),
                    ("PT", "Part Time"),
                    ("CT", "Contract"),
                    ("RM", "Remote"),
                ],
                default="FT",
                max_length=2,
            ),
        ),
    ]
