# Generated by Django 4.2.27 on 2026-01-12 09:11
# Modified to be state-only since columns already exist in database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        # Use SeparateDatabaseAndState because columns were added manually
        # This only updates Django's internal state, not the actual database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="attendance",
                    name="current_session_type",
                    field=models.CharField(
                        blank=True,
                        help_text="Current session type (WEB/REMOTE)",
                        max_length=20,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="attendance",
                    name="daily_sessions_count",
                    field=models.IntegerField(default=0, help_text="Number of sessions today"),
                ),
                migrations.AddField(
                    model_name="attendance",
                    name="max_daily_sessions",
                    field=models.IntegerField(
                        default=3, help_text="Maximum allowed sessions per day"
                    ),
                ),
            ],
            database_operations=[
                # No database operations - columns already exist
            ],
        ),
    ]
