# Generated by Django 4.2.23 on 2025-12-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_account_number_employee_badge_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in", models.DateTimeField(blank=True, null=True)),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="Absent", max_length=20)),
                (
                    "location_in",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_out",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
