# Generated by Django 4.2.27 on 2026-01-12 11:54
# Modified to be idempotent for staging deployment

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def safe_alter_locationlog(apps, schema_editor):
    """
    Idempotent migration for LocationLog table.
    Checks if columns/indexes exist before creating them.
    """
    from django.db import connection

    def column_exists(table_name, column_name):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                """,
                [table_name, column_name],
            )
            return cursor.fetchone() is not None

    def index_exists(index_name):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT indexname FROM pg_indexes
                WHERE indexname = %s
                """,
                [index_name],
            )
            return cursor.fetchone() is not None

    with connection.cursor() as cursor:
        table = "employees_locationlog"

        # Add accuracy column if missing
        if not column_exists(table, "accuracy"):
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN accuracy DOUBLE PRECISION NULL")
            print("[OK] Added accuracy column")
        else:
            print("[INFO] accuracy column already exists")

        # Add address column if missing
        if not column_exists(table, "address"):
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN address TEXT NULL")
            print("[OK] Added address column")
        else:
            print("[INFO] address column already exists")

        # Add attendance_session_id FK if missing
        if not column_exists(table, "attendance_session_id"):
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN attendance_session_id BIGINT NULL")
            cursor.execute(
                f"""
                ALTER TABLE {table} ADD CONSTRAINT
                employees_location_attendance_ses_fk
                FOREIGN KEY (attendance_session_id)
                REFERENCES employees_attendancesession(id)
                DEFERRABLE INITIALLY DEFERRED
                """
            )
            print("[OK] Added attendance_session_id FK")
        else:
            print("[INFO] attendance_session_id column already exists")

        # Add created_at column if missing
        if not column_exists(table, "created_at"):
            cursor.execute(
                f"""
                ALTER TABLE {table}
                ADD COLUMN created_at TIMESTAMP WITH TIME ZONE
                DEFAULT NOW() NOT NULL
                """
            )
            print("[OK] Added created_at column")
        else:
            print("[INFO] created_at column already exists")

        # Add is_valid column if missing
        if not column_exists(table, "is_valid"):
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN is_valid BOOLEAN DEFAULT TRUE NOT NULL")
            print("[OK] Added is_valid column")
        else:
            print("[INFO] is_valid column already exists")

        # Add log_type column if missing
        if not column_exists(table, "log_type"):
            cursor.execute(
                f"""
                ALTER TABLE {table}
                ADD COLUMN log_type VARCHAR(20) DEFAULT 'MANUAL' NOT NULL
                """
            )
            print("[OK] Added log_type column")
        else:
            print("[INFO] log_type column already exists")

        # Add indexes if missing
        idx1 = "employees_l_employe_d862f5_idx"
        if not index_exists(idx1):
            cursor.execute(f"CREATE INDEX {idx1} ON {table} (employee_id, timestamp)")
            print(f"[OK] Created index {idx1}")
        else:
            print(f"[INFO] Index {idx1} already exists")

        idx2 = "employees_l_attenda_bc2cae_idx"
        if not index_exists(idx2):
            cursor.execute(f"CREATE INDEX {idx2} ON {table} (attendance_session_id, log_type)")
            print(f"[OK] Created index {idx2}")
        else:
            print(f"[INFO] Index {idx2} already exists")

    print("[OK] LocationLog schema update complete")


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_add_missing_attendance_fields"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to:
        # 1. Run safe idempotent Python for DB operations
        # 2. Tell Django state what the schema should look like
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_alter_locationlog, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterModelOptions(
                    name="locationlog",
                    options={"ordering": ["-timestamp"]},
                ),
                migrations.AddField(
                    model_name="locationlog",
                    name="accuracy",
                    field=models.FloatField(blank=True, help_text="GPS accuracy in meters", null=True),
                ),
                migrations.AddField(
                    model_name="locationlog",
                    name="address",
                    field=models.TextField(blank=True, help_text="Reverse geocoded address", null=True),
                ),
                migrations.AddField(
                    model_name="locationlog",
                    name="attendance_session",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_location_logs",
                        to="employees.attendancesession",
                    ),
                ),
                migrations.AddField(
                    model_name="locationlog",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="locationlog",
                    name="is_valid",
                    field=models.BooleanField(default=True, help_text="Whether this location is valid"),
                ),
                migrations.AddField(
                    model_name="locationlog",
                    name="log_type",
                    field=models.CharField(
                        choices=[
                            ("CLOCK_IN", "Clock In"),
                            ("CLOCK_OUT", "Clock Out"),
                            ("HOURLY", "Hourly Tracking"),
                            ("MANUAL", "Manual Update"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                migrations.AlterField(
                    model_name="locationlog",
                    name="latitude",
                    field=models.DecimalField(decimal_places=7, max_digits=10),
                ),
                migrations.AlterField(
                    model_name="locationlog",
                    name="longitude",
                    field=models.DecimalField(decimal_places=7, max_digits=10),
                ),
                migrations.AddIndex(
                    model_name="locationlog",
                    index=models.Index(
                        fields=["employee", "timestamp"],
                        name="employees_l_employe_d862f5_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="locationlog",
                    index=models.Index(
                        fields=["attendance_session", "log_type"],
                        name="employees_l_attenda_bc2cae_idx",
                    ),
                ),
            ],
        ),
    ]
