# Generated by Django 4.2.23 on 2025-12-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_locationlog_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeIDProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhar_front",
                    models.ImageField(
                        blank=True, null=True, upload_to="id_proofs/aadhar/"
                    ),
                ),
                (
                    "aadhar_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="id_proofs/aadhar/"
                    ),
                ),
                (
                    "pan_card",
                    models.ImageField(
                        blank=True, null=True, upload_to="id_proofs/pan/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_proofs",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
