# Generated by Django 4.2.27 on 2026-01-12 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_add_missing_attendance_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="locationlog",
            name="accuracy",
            field=models.FloatField(
                blank=True, help_text="GPS accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="locationlog",
            name="address",
            field=models.TextField(
                blank=True, help_text="Reverse geocoded address", null=True
            ),
        ),
        migrations.AddField(
            model_name="locationlog",
            name="attendance_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_location_logs",
                to="employees.attendancesession",
            ),
        ),
        migrations.AddField(
            model_name="locationlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationlog",
            name="is_valid",
            field=models.BooleanField(
                default=True, help_text="Whether this location is valid"
            ),
        ),
        migrations.AddField(
            model_name="locationlog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("CLOCK_IN", "Clock In"),
                    ("CLOCK_OUT", "Clock Out"),
                    ("HOURLY", "Hourly Tracking"),
                    ("MANUAL", "Manual Update"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locationlog",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="locationlog",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["employee", "timestamp"], name="employees_l_employe_d862f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["attendance_session", "log_type"],
                name="employees_l_attenda_bc2cae_idx",
            ),
        ),
    ]
