# Generated by Django 4.2.23 on 2025-12-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_employeeidproof"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_avatars/"
            ),
        ),
    ]
