# Generated by Django 4.2.27 on 2026-01-13 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_locationlog_options_locationlog_accuracy_and_more"),
        ("employees", "0003_add_missing_attendance_fields"),
    ]

    operations = []
