# Generated by Django 4.2.23 on 2025-12-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_leaverequest_leavebalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[("CL", "Casual Leave"), ("SL", "Sick Leave")], max_length=3
            ),
        ),
    ]
