# Generated by Django 4.2.27 on 2026-01-13 06:22

from django.db import migrations


def update_max_sessions_to_3(apps, schema_editor):
    """Update all existing attendance records to have max_daily_sessions = 3"""
    Attendance = apps.get_model('employees', 'Attendance')
    Attendance.objects.filter(max_daily_sessions__gt=3).update(max_daily_sessions=3)


def reverse_update_max_sessions(apps, schema_editor):
    """Reverse migration - set back to 5 (previous common default)"""
    Attendance = apps.get_model('employees', 'Attendance')
    Attendance.objects.filter(max_daily_sessions=3).update(max_daily_sessions=5)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_update_max_sessions_to_3'),
    ]

    operations = [
        migrations.RunPython(
            update_max_sessions_to_3,
            reverse_update_max_sessions,
        ),
    ]
