# Generated by Django 4.2.23 on 2025-12-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_leaverequest_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="annual_ctc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Annual CTC",
            ),
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="Select any date in the month")),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="payslips/"),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
    ]
