# Generated by Django 4.2.27 on 2026-01-13 06:54

from django.db import migrations


def check_and_add_columns_safely(apps, schema_editor):
    """
    Safely add columns that might already exist in the staging database.
    This handles the case where staging DB has columns that migrations think don't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if current_session_type column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='employees_attendance' 
            AND column_name='current_session_type'
        """)
        
        if not cursor.fetchone():
            print("Adding current_session_type column...")
            cursor.execute("""
                ALTER TABLE employees_attendance 
                ADD COLUMN current_session_type VARCHAR(20) NULL
            """)
            print("✅ Added current_session_type column")
        else:
            print("✅ current_session_type column already exists, skipping")
        
        # Check if daily_sessions_count column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='employees_attendance' 
            AND column_name='daily_sessions_count'
        """)
        
        if not cursor.fetchone():
            print("Adding daily_sessions_count column...")
            cursor.execute("""
                ALTER TABLE employees_attendance 
                ADD COLUMN daily_sessions_count INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added daily_sessions_count column")
        else:
            print("✅ daily_sessions_count column already exists, skipping")
        
        # Check if max_daily_sessions column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='employees_attendance' 
            AND column_name='max_daily_sessions'
        """)
        
        if not cursor.fetchone():
            print("Adding max_daily_sessions column...")
            cursor.execute("""
                ALTER TABLE employees_attendance 
                ADD COLUMN max_daily_sessions INTEGER DEFAULT 3 NOT NULL
            """)
            print("✅ Added max_daily_sessions column")
        else:
            print("✅ max_daily_sessions column already exists, skipping")
            
            # Update existing records to have max 3 sessions
            cursor.execute("""
                UPDATE employees_attendance 
                SET max_daily_sessions = 3 
                WHERE max_daily_sessions > 3
            """)
            updated_count = cursor.rowcount
            print(f"✅ Updated {updated_count} records to max_daily_sessions=3")
        
        # Check if total_working_hours column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='employees_attendance' 
            AND column_name='total_working_hours'
        """)
        
        if not cursor.fetchone():
            print("Adding total_working_hours column...")
            cursor.execute("""
                ALTER TABLE employees_attendance 
                ADD COLUMN total_working_hours DECIMAL(5,2) DEFAULT 0.00 NOT NULL
            """)
            print("✅ Added total_working_hours column")
        else:
            print("✅ total_working_hours column already exists, skipping")


def reverse_column_additions(apps, schema_editor):
    """
    Reverse the column additions - but be careful not to drop if they were already there
    """
    print("⚠️ Reverse migration - columns will be preserved to avoid data loss")
    print("Manual cleanup required if columns need to be removed")


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_update_existing_max_sessions'),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_columns_safely,
            reverse_column_additions,
        ),
    ]
