# Generated by Django 4.2.27 on 2026-01-13 07:09
# Modified to be safe for staging deployment where columns may already exist

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0008_fix_duplicate_column_migration"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to only update Django's state
        # The actual database columns are handled by migration 0008
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="attendance",
                    name="total_working_hours",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total working hours for the day",
                        max_digits=5,
                    ),
                ),
                migrations.AlterField(
                    model_name="attendance",
                    name="current_session_type",
                    field=models.CharField(
                        blank=True,
                        choices=[("WEB", "Web"), ("REMOTE", "Remote")],
                        help_text="Current session type (WEB/REMOTE)",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                # Database operations are handled by the safe migration 0008
                # This only ensures Django's migration state is correct
            ],
        ),
    ]
