# Generated by Django 4.2.27 on 2026-01-13 07:15
# Special migration to handle staging database state conflicts

from django.db import migrations


def reset_staging_migration_state(apps, schema_editor):
    """
    This migration handles the complex staging database state where:
    1. Columns already exist in the database
    2. Migration history is inconsistent
    3. We need to ensure Django's state matches the actual database
    """
    from django.db import connection
    
    print("🔄 Resetting migration state for staging deployment...")
    
    with connection.cursor() as cursor:
        # Get current table structure
        cursor.execute("""
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns 
            WHERE table_name='employees_attendance'
            ORDER BY ordinal_position
        """)
        
        columns = cursor.fetchall()
        column_names = [col[0] for col in columns]
        
        print(f"📋 Current attendance table columns: {len(column_names)}")
        for col in columns:
            print(f"  - {col[0]} ({col[1]}) {'NULL' if col[2] == 'YES' else 'NOT NULL'}")
        
        # Ensure all required columns exist with correct defaults
        required_columns = {
            'current_session_type': "VARCHAR(20) NULL",
            'daily_sessions_count': "INTEGER DEFAULT 0 NOT NULL",
            'max_daily_sessions': "INTEGER DEFAULT 3 NOT NULL", 
            'total_working_hours': "DECIMAL(5,2) DEFAULT 0.00 NOT NULL",
            'location_tracking_active': "BOOLEAN DEFAULT FALSE NOT NULL",
            'location_tracking_end_time': "TIMESTAMP NULL",
            'user_timezone': "VARCHAR(50) DEFAULT 'Asia/Kolkata' NOT NULL"
        }
        
        for col_name, col_definition in required_columns.items():
            if col_name not in column_names:
                print(f"➕ Adding missing column: {col_name}")
                cursor.execute(f"""
                    ALTER TABLE employees_attendance 
                    ADD COLUMN {col_name} {col_definition}
                """)
            else:
                print(f"✅ Column exists: {col_name}")
        
        # Update max_daily_sessions to 3 for existing records
        cursor.execute("""
            UPDATE employees_attendance 
            SET max_daily_sessions = 3 
            WHERE max_daily_sessions > 3
        """)
        updated_count = cursor.rowcount
        if updated_count > 0:
            print(f"📝 Updated {updated_count} records to max_daily_sessions=3")
        
        # Ensure user_timezone has default value
        cursor.execute("""
            UPDATE employees_attendance 
            SET user_timezone = 'Asia/Kolkata' 
            WHERE user_timezone IS NULL OR user_timezone = ''
        """)
        timezone_updated = cursor.rowcount
        if timezone_updated > 0:
            print(f"🌍 Set timezone for {timezone_updated} records")
        
        print("✅ Staging database state reset completed successfully")


def reverse_staging_reset(apps, schema_editor):
    """
    Reverse operation - minimal since we don't want to break existing data
    """
    print("⚠️ Reverse migration - preserving existing database state")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_attendance_total_working_hours_and_more'),
    ]

    operations = [
        migrations.RunPython(
            reset_staging_migration_state,
            reverse_staging_reset,
        ),
    ]
