# Generated by Django 4.2.23 on 2025-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_handbooksection_policysection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("HALF_DAY", "Half Day"),
                    ("LEAVE", "On Leave"),
                    ("WFH", "Work From Home"),
                    ("ON_DUTY", "On Duty"),
                    ("WEEKLY_OFF", "Weekly Off"),
                    ("HOLIDAY", "Holiday"),
                ],
                default="ABSENT",
                max_length=20,
            ),
        ),
    ]
