# Generated by Django 4.2.23 on 2025-12-18 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0010_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="leavebalance",
            name="casual_leave",
        ),
        migrations.RemoveField(
            model_name="leavebalance",
            name="sick_leave",
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="carry_forward_leave",
            field=models.FloatField(
                default=0.0, help_text="Leave carried from previous year"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="casual_leave_allocated",
            field=models.FloatField(
                default=12.0, help_text="Total CL allocated per year"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="casual_leave_used",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="comp_off_allocated",
            field=models.FloatField(default=0.0, help_text="Comp off earned"),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="comp_off_used",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="earned_leave_allocated",
            field=models.FloatField(
                default=12.0, help_text="Total EL allocated per year"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="earned_leave_used",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="lapsed_leave",
            field=models.FloatField(default=0.0, help_text="Leave that expired"),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="sick_leave_allocated",
            field=models.FloatField(
                default=12.0, help_text="Total SL allocated per year"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="sick_leave_used",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="admin_comment",
            field=models.TextField(
                blank=True, help_text="Admin/Manager remarks", null=True
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approval_level",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("HR", "HR/Admin")],
                default="MANAGER",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="duration",
            field=models.CharField(
                choices=[("FULL", "Full Day"), ("HALF", "Half Day")],
                default="FULL",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="supporting_document",
            field=models.FileField(blank=True, null=True, upload_to="leave_documents/"),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CL", "Casual Leave"),
                    ("SL", "Sick Leave"),
                    ("EL", "Earned Leave"),
                    ("CO", "Comp Off"),
                    ("UL", "Unpaid Leave"),
                    ("OT", "Others"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
