# Generated by Django 4.2.23 on 2025-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_alter_leaverequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(
                choices=[
                    ("INDIA", "India"),
                    ("US", "United States"),
                    ("DHAKA", "Dhaka, Bangladesh"),
                    ("UK", "United Kingdom"),
                    ("GLOBAL", "Global"),
                ],
                default="INDIA",
                help_text="Employee work location for holiday filtering",
                max_length=20,
            ),
        ),
    ]
