# Generated by Django 4.2.23 on 2025-12-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_shiftschedule"),
        ("employees", "0012_employee_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="shift",
        ),
        migrations.AddField(
            model_name="attendance",
            name="early_departure_minutes",
            field=models.IntegerField(default=0, help_text="Minutes before shift end"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_early_departure",
            field=models.BooleanField(
                default=False, help_text="Left before shift end time"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_late",
            field=models.BooleanField(
                default=False, help_text="Marked late based on shift timing"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="late_by_minutes",
            field=models.IntegerField(
                default=0, help_text="Minutes late after grace period"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned shift schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="companies.shiftschedule",
            ),
        ),
    ]
