# Generated by Django 4.2.23 on 2025-12-21 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0013_remove_employee_shift_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date to be regularized")),
                (
                    "check_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="New Check-In Time"
                    ),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="New Check-Out Time"
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for regularization")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Manager Remarks"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_regularizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regularization_requests",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
