# Generated by Django 4.2.23 on 2026-01-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0014_leaverequest_approval_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_anniversary_email_year",
            field=models.IntegerField(
                blank=True, help_text="Year of last sent anniversary email", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_birthday_email_year",
            field=models.IntegerField(
                blank=True, help_text="Year of last sent birthday email", null=True
            ),
        ),
    ]
