# Generated by Django 4.2.23 on 2025-12-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "companies",
            "0007_rename_companies_h_company_f6931c_idx_companies_h_company_a18c66_idx_and_more",
        ),
        ("employees", "0014_regularizationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="location_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee work location (NEW)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees_new",
                to="companies.location",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.CharField(
                choices=[
                    ("INDIA", "India"),
                    ("US", "United States"),
                    ("DHAKA", "Dhaka, Bangladesh"),
                    ("UK", "United Kingdom"),
                    ("GLOBAL", "Global"),
                ],
                default="INDIA",
                help_text="Employee work location for holiday filtering (OLD)",
                max_length=20,
            ),
        ),
    ]
