# Generated by Django 4.2.23 on 2026-01-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_last_anniversary_email_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_address',
            field=models.TextField(blank=True, null=True, verbose_name='Current Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_edited',
            field=models.BooleanField(default=False, help_text='Has the employee edited their profile?'),
        ),
    ]
