# Generated by Django 4.2.23 on 2025-12-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0007_rename_companies_h_company_f6931c_idx_companies_h_company_a18c66_idx_and_more",
        ),
        ("employees", "0015_employee_location_new_alter_employee_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="location",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="location_new",
            new_name="location",
        ),
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee work location for holiday filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="companies.location",
            ),
        ),
    ]
