# Generated by Django 4.2.23 on 2026-01-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_last_anniversary_email_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal Email Address for information only', max_length=254, null=True, verbose_name='Personal Email'),
        ),
    ]
