# Generated by Django 4.2.23 on 2025-12-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0016_remove_employee_location_new_alter_employee_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="shift_schedule",
            field=models.CharField(
                blank=True,
                help_text="Assigned shift schedule (e.g., 09:00 AM - 06:00 PM)",
                max_length=100,
                null=True,
            ),
        ),
    ]
