# Generated by Django 4.2.23 on 2025-12-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_shiftschedule_allowed_late_logins_and_more"),
        ("employees", "0017_alter_employee_shift_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_grace_used",
            field=models.BooleanField(
                default=False, help_text="Logged in late but within grace period"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_half_day_late",
            field=models.BooleanField(
                default=False, help_text="Marked as Half Day due to late login exceed"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="assigned_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="companies.shiftschedule",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="shift_schedule",
            field=models.CharField(
                blank=True,
                help_text="Legacy: Assigned shift schedule (e.g., 09:00 AM - 06:00 PM)",
                max_length=100,
                null=True,
            ),
        ),
    ]
