# Generated by Django 4.2.23 on 2026-01-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_current_address_employee_profile_edited'),
        ('employees', '0017_employee_personal_email'),
    ]

    operations = [
    ]
