# Generated by Django 4.2.23 on 2026-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_merge_20260121_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], default='FULL', max_length=12),
        ),
    ]
