# Generated by Django 4.2.23 on 2025-12-22 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "employees",
            "0018_attendance_is_grace_used_attendance_is_half_day_late_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
