# Generated by Django 4.2.23 on 2025-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0019_alter_employee_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_in_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of clock-in attempts (max 3)"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="location_tracking_active",
            field=models.BooleanField(
                default=False, help_text="Whether location tracking is currently active"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="location_tracking_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When location tracking should stop", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("HALF_DAY", "Half Day"),
                    ("LEAVE", "On Leave"),
                    ("WFH", "Work From Home"),
                    ("ON_DUTY", "On Duty"),
                    ("WEEKLY_OFF", "Weekly Off"),
                    ("HOLIDAY", "Holiday"),
                    ("MISSING_PUNCH", "Missing Punch"),
                ],
                default="ABSENT",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
    ]
