# Generated by Django 4.2.23 on 2025-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0020_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("RESIGNED", "Resigned"),
                    ("ABSCONDED", "Absconded"),
                    ("TERMINATED", "Terminated"),
                ],
                default="ACTIVE",
                help_text="Current employment status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="exit_date",
            field=models.DateField(
                blank=True,
                help_text="Date when employee exited the organization",
                null=True,
                verbose_name="Last Working Date",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="exit_note",
            field=models.TextField(
                blank=True,
                help_text="Detailed reason for employee exit",
                null=True,
                verbose_name="Exit Reason/Note",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether employee is currently active in the organization",
            ),
        ),
    ]
