# Generated by Django 4.2.23 on 2025-12-24 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0021_employee_employment_status_employee_exit_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExitInitiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exit_type",
                    models.CharField(
                        choices=[
                            ("RESIGNATION", "Resignation"),
                            ("ABSCONDED", "Absconded"),
                            ("TERMINATED", "Terminated"),
                        ],
                        help_text="Type of exit",
                        max_length=20,
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(help_text="Date when exit was initiated"),
                ),
                ("exit_note", models.TextField(help_text="Reason for exit")),
                (
                    "notice_period_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Notice period in days (for absconding/termination)",
                        null=True,
                    ),
                ),
                (
                    "last_working_day",
                    models.DateField(
                        blank=True,
                        help_text="Calculated or approved last working day",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        help_text="Status of exit request (mainly for resignations)",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (if applicable)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_exits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_initiatives",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exit Initiative",
                "verbose_name_plural": "Exit Initiatives",
                "ordering": ["-created_at"],
            },
        ),
    ]
