# Generated by Django 4.2.23 on 2026-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_payslip_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
    ]
