# Generated by Django 4.2.23 on 2026-01-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_employee_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='monthly_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
