# Generated by Django 4.2.23 on 2025-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0022_exitinitiative"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="week_off_friday",
            field=models.BooleanField(default=False, help_text="Friday is week-off"),
        ),
        migrations.AddField(
            model_name="employee",
            name="week_off_monday",
            field=models.BooleanField(default=False, help_text="Monday is week-off"),
        ),
        migrations.AddField(
            model_name="employee",
            name="week_off_saturday",
            field=models.BooleanField(default=True, help_text="Saturday is week-off"),
        ),
        migrations.AddField(
            model_name="employee",
            name="week_off_sunday",
            field=models.BooleanField(default=True, help_text="Sunday is week-off"),
        ),
        migrations.AddField(
            model_name="employee",
            name="week_off_thursday",
            field=models.BooleanField(default=False, help_text="Thursday is week-off"),
        ),
        migrations.AddField(
            model_name="employee",
            name="week_off_tuesday",
            field=models.BooleanField(default=False, help_text="Tuesday is week-off"),
        ),
        migrations.AddField(
            model_name="employee",
            name="week_off_wednesday",
            field=models.BooleanField(default=False, help_text="Wednesday is week-off"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CL", "Casual Leave"),
                    ("SL", "Sick Leave"),
                    ("EL", "Earned Leave"),
                    ("CO", "Comp Off"),
                    ("UL", "Unpaid Leave (LOP)"),
                    ("OT", "Others"),
                ],
                max_length=2,
            ),
        ),
    ]
