# Generated by Django 4.2.23 on 2025-12-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees",
            "0023_employee_week_off_friday_employee_week_off_monday_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="probation_completion_date",
            field=models.DateField(
                blank=True, help_text="Date when probation was completed", null=True
            ),
        ),
        migrations.CreateModel(
            name="JobHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="e.g. Promotion, Transfer, Joined",
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_history",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
