# Generated by Django 4.2.23 on 2026-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_auto_20260128_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='max_daily_clocks',
            field=models.IntegerField(default=999, help_text='Maximum allowed clock-ins per day'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='max_daily_sessions',
            field=models.IntegerField(default=999, help_text='Maximum allowed sessions per day'),
        ),
    ]
