# Generated by Django 4.2.23 on 2025-12-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0024_employee_probation_completion_date_jobhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="probation_completion_date",
        ),
        migrations.DeleteModel(
            name="JobHistory",
        ),
    ]
