# Generated by Django 4.2.23 on 2026-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_alter_attendance_max_daily_clocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Conveyance'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='lta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Conveyance Allowance'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Special Allowance'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Medical Allowance'),
        ),
    ]
