# Generated by Django 4.2.23 on 2025-12-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0025_remove_employee_probation_completion_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use EmergencyContact model instead",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of emergency contact", max_length=100
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Contact phone number", max_length=15),
                ),
                (
                    "relationship",
                    models.CharField(
                        help_text="Relationship to employee (e.g., Spouse, Parent, Sibling)",
                        max_length=50,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary emergency contact"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
    ]
