# Generated by Django 4.2.23 on 2026-01-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_auto_20260128_1715'),
        ('employees', '0026_alter_payslip_conveyance_allowance_alter_payslip_lta_and_more'),
    ]

    operations = [
    ]
