# Generated by Django 4.2.23 on 2026-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_merge_20260130_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='combined_sick_casual_allocated',
            field=models.FloatField(default=0.0, help_text='Combined SL/CL allocation for companies like Bluebix'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='combined_sick_casual_used',
            field=models.FloatField(default=0.0, help_text='Combined SL/CL used'),
        ),
    ]
