# Generated by Django 4.2.23 on 2026-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0027_alter_employee_badge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="daily_clock_count",
            field=models.IntegerField(
                default=0, help_text="Number of valid clock-ins today"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_currently_clocked_in",
            field=models.BooleanField(
                default=False, help_text="Currently clocked in status"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="max_daily_clocks",
            field=models.IntegerField(
                default=3, help_text="Maximum allowed clock-ins per day"
            ),
        ),
    ]
