# Generated by Django 4.2.23 on 2026-01-07 12:45
# Modified to be idempotent - safely handles existing columns

from django.db import migrations, models, connection


def column_exists(table_name, column_name):
    """Check if a column exists in the database table."""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = %s
        """,
            [table_name, column_name],
        )
        return cursor.fetchone() is not None


class SafeAddField(migrations.AddField):
    """AddField that skips if column already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table

        # Get the actual column name - use db_column if set, otherwise use field name
        column_name = getattr(self.field, "db_column", None) or self.name

        if column_exists(table_name, column_name):
            # Column already exists, skip
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0027_alter_employee_badge_id"),
    ]

    operations = [
        SafeAddField(
            model_name="attendance",
            name="daily_clock_count",
            field=models.IntegerField(
                default=0, help_text="Number of valid clock-ins today"
            ),
        ),
        SafeAddField(
            model_name="attendance",
            name="is_currently_clocked_in",
            field=models.BooleanField(
                default=False, help_text="Currently clocked in status"
            ),
        ),
        SafeAddField(
            model_name="attendance",
            name="max_daily_clocks",
            field=models.IntegerField(
                default=3, help_text="Maximum allowed clock-ins per day"
            ),
        ),
    ]
