# Generated by Django 4.2.27 on 2026-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0028_add_missing_attendance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="local_clock_in_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Clock-in time in employee's local timezone",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="local_clock_out_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Clock-out time in employee's local timezone",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="user_timezone",
            field=models.CharField(
                default="Asia/Kolkata",
                help_text="Employee's timezone when clocking in",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CL", "Casual Leave"),
                    ("SL", "Sick Leave"),
                    ("CO", "Comp Off"),
                    ("UL", "Unpaid Leave (LOP)"),
                    ("OT", "Others"),
                ],
                max_length=2,
            ),
        ),
    ]
