# Generated by Django 4.2.23 on 2026-02-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_add_combined_sick_casual_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='ID as registered in the biometric machine', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='current_session_type',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('REMOTE', 'Remote'), ('BIOMETRIC', 'Biometric Device'), ('MOBILE', 'Mobile App')], help_text='Current session type (WEB/REMOTE/BIOMETRIC)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('WFH', 'Work From Home'), ('ON_DUTY', 'On Duty'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday'), ('MISSING_PUNCH', 'Missing Punch'), ('DOOR_OPEN', 'Door Access Only')], default='ABSENT', max_length=20),
        ),
    ]
