# Generated by Django 4.2.27 on 2026-02-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_approvalworkflow'),
        ('employees', '0029_employee_biometric_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='current_step',
            field=models.PositiveIntegerField(default=1, help_text='Current step in the approval workflow'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.approvalworkflow'),
        ),
    ]
