# Generated by Django 4.2.23 on 2026-01-10
# Migration to add user_timezone field to Attendance model

from django.db import migrations, models, connection


def column_exists(table_name, column_name):
    """Check if a column exists in the database table."""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = %s
        """,
            [table_name, column_name],
        )
        return cursor.fetchone() is not None


class SafeAddField(migrations.AddField):
    """AddField that skips if column already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        column_name = getattr(self.field, "db_column", None) or self.name

        if column_exists(table_name, column_name):
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0030_alter_leaverequest_leave_type"),
    ]

    operations = [
        SafeAddField(
            model_name="attendance",
            name="user_timezone",
            field=models.CharField(
                default="Asia/Kolkata",
                max_length=50,
                help_text="User's timezone when attendance was recorded",
            ),
        ),
    ]
