# Generated by Django 4.2.27 on 2026-01-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_timezone',
            field=models.CharField(default='Asia/Kolkata', help_text="User's timezone when clocking in", max_length=50),
        ),
    ]
