# Generated by Django 4.2.23 on 2026-02-03 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_leaverequest_current_step_leaverequest_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('DESIGNATION', 'Designation Change'), ('CTC', 'CTC Change'), ('JOINING', 'Joined'), ('PROBATION', 'Probation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('previous_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Work History',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
