# Generated by Django 4.2.27 on 2026-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_workhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief professional summary or bio', max_length=1000, null=True, verbose_name='About Me'),
        ),
    ]
