# Generated by Django 4.2.27 on 2026-01-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_attendance_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in_attempts',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='daily_clock_count',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='max_daily_clocks',
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_session_type',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('REMOTE', 'Remote')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='daily_sessions_count',
            field=models.IntegerField(default=0, help_text='Number of clock-in/out sessions today'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='max_daily_sessions',
            field=models.IntegerField(default=3, help_text='Maximum allowed sessions per day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_break_hours',
            field=models.FloatField(default=0.0, help_text='Total break time between sessions'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_hours',
            field=models.FloatField(default=0.0, help_text='Total working hours for the day'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('WFH', 'Work From Home'), ('ON_DUTY', 'On Duty'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday'), ('MISSING_PUNCH', 'Missing Punch'), ('HYBRID', 'Hybrid (Web + Remote)')], default='ABSENT', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Session number for the day (1, 2, 3)')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('WEB', 'Web/Office'), ('REMOTE', 'Remote/WFH')], max_length=10)),
                ('location_in', models.CharField(blank=True, max_length=255, null=True)),
                ('location_out', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_hours', models.FloatField(default=0.0, help_text='Duration of this session in hours')),
                ('user_timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='employees.attendance')),
            ],
            options={
                'ordering': ['session_number'],
                'unique_together': {('attendance', 'session_number')},
            },
        ),
    ]
