# Generated by Django 4.2.23 on 2026-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_workhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='last_accrual_month',
            field=models.IntegerField(blank=True, help_text='Last month leaves were accrued', null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_accrual_year',
            field=models.IntegerField(blank=True, help_text='Last year leaves were accrued', null=True),
        ),
    ]
