# Generated by Django 4.2.23 on 2026-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_leavebalance_last_accrual_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pseudo_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pseudo Name'),
        ),
    ]
