# Generated by Django 4.2.27 on 2026-01-10 13:02

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_remove_attendance_clock_in_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
