# Generated by Django 4.2.27 on 2026-01-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_auto_20260110_1832'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='attendancesession',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='location_in',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='location_out',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='user_timezone',
        ),
        
        # Add new fields
        migrations.AddField(
            model_name='attendancesession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='employees.employee', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default='2026-01-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clock_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration of this session in minutes'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='location_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Alter existing fields
        migrations.AlterField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('WEB', 'Web/Office'), ('REMOTE', 'Remote/WFH')], max_length=50),
        ),
        
        # Update Meta options
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['date', 'session_number']},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('employee', 'date', 'session_number')},
        ),
        migrations.AlterModelTable(
            name='attendancesession',
            table='employees_attendancesession',
        ),
        
        # Create SessionLocationLog model
        migrations.CreateModel(
            name='SessionLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='employees.attendancesession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]