# Generated by Django 4.2.23 on 2026-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_employee_pseudo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_activity_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Enable activity tracking for this employee'),
        ),
    ]
