# Generated by Django 4.2.27 on 2026-03-30 09:51

from django.db import migrations

def remove_hyphens_from_badge_ids(apps, schema_editor):
    # This function is now empty to unblock production deployment.
    # We will run the data cleanup via a separate management command
    # to avoid locking tables during standard migrations.
    pass

def reverse_remove_hyphens_from_badge_ids(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_remove_activity_tracking_enabled'),
    ]

    operations = [
        migrations.RunPython(remove_hyphens_from_badge_ids, reverse_remove_hyphens_from_badge_ids),
    ]
