# Generated by Django 4.2.27 on 2026-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_remove_hyphens_from_badge_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationrequest',
            name='change_type',
            field=models.CharField(choices=[('MISSED_PUNCH', 'Missed Punch'), ('SYSTEM_ERROR', 'System Error'), ('WEB_CLONING', 'Web Cloning'), ('REMOTE_CLOCK_IN', 'Remote Clock-in'), ('OTHER', 'Other')], default='MISSED_PUNCH', max_length=20, verbose_name='Change Type'),
        ),
    ]
