# Generated by Django 4.2.27 on 2026-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_payslip_arrears_payslip_asset_damage_recovery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('WFH', 'Work From Home'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_DUTY', 'On Duty'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday'), ('MISSING_PUNCH', 'Missing Punch'), ('DOOR_OPEN', 'Door Access Only')], default='ABSENT', max_length=20),
        ),
    ]
