# Generated by Django 4.2.27 on 2026-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
