# Generated by Django 4.2.27 on 2026-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_support_agent',
            field=models.BooleanField(default=False, help_text='Designate this employee as a system support agent.', verbose_name='Support Agent'),
        ),
    ]
