# Generated by Django 4.2.27 on 2026-06-02 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0042_employee_is_support_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('COMBINED', 'Combined Sick/Casual'), ('UL', 'Unpaid Leave (LOP)'), ('OD', 'On Duty'), ('OT', 'Others')], max_length=10)),
                ('amount', models.FloatField(help_text='Number of days added or subtracted')),
                ('reason', models.TextField(blank=True, help_text='e.g., Monthly Accrual, Leave Request Approved, Manual adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who made the change. Null if system (accrual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_transactions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_transactions', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
