# Generated by Django 4.2.27 on 2026-06-02 12:35

from django.db import migrations
from django.utils import timezone


def populate_retroactive_history(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    LeaveTransaction = apps.get_model('employees', 'LeaveTransaction')

    # Get all active employees
    employees = Employee.objects.filter(is_active=True)

    months = [1, 2, 3, 4, 5]
    year = 2026

    for emp in employees:
        company_name = emp.company.name.lower()
        for month in months:
            reason = f"Monthly Accrual ({month}/2026)"

            # Avoid double-populating if this specific month log already exists
            if LeaveTransaction.objects.filter(employee=emp, reason=reason).exists():
                continue

            created_at = timezone.datetime(year, month, 1, 9, 0, tzinfo=timezone.get_current_timezone())

            if "petabytz" in company_name:
                LeaveTransaction.objects.create(
                    employee=emp,
                    transaction_type="CREDIT",
                    leave_type="SL",
                    amount=1.0,
                    reason=reason,
                    created_at=created_at
                )
                LeaveTransaction.objects.create(
                    employee=emp,
                    transaction_type="CREDIT",
                    leave_type="CL",
                    amount=1.0,
                    reason=reason,
                    created_at=created_at
                )
            elif "bluebix" in company_name or "softstandard" in company_name:
                LeaveTransaction.objects.create(
                    employee=emp,
                    transaction_type="CREDIT",
                    leave_type="COMBINED",
                    amount=1.0,
                    reason=reason,
                    created_at=created_at
                )
            else:
                LeaveTransaction.objects.create(
                    employee=emp,
                    transaction_type="CREDIT",
                    leave_type="SL",
                    amount=1.0,
                    reason=reason,
                    created_at=created_at
                )
                LeaveTransaction.objects.create(
                    employee=emp,
                    transaction_type="CREDIT",
                    leave_type="CL",
                    amount=1.0,
                    reason=reason,
                    created_at=created_at
                )

def rollback_retroactive_history(apps, schema_editor):
    LeaveTransaction = apps.get_model('employees', 'LeaveTransaction')
    # Delete the created accruals if we rollback
    LeaveTransaction.objects.filter(reason__contains="Monthly Accrual (").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_leavetransaction'),
    ]

    operations = [
        migrations.RunPython(populate_retroactive_history, rollback_retroactive_history),
    ]
