# Generated by Django 4.2.27 on 2026-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_populate_retroactive_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularizationrequest',
            name='change_type',
            field=models.CharField(choices=[('MISSED_PUNCH', 'Missed Punch'), ('SYSTEM_ERROR', 'System Error'), ('WEB_CLONING', 'Web Cloning'), ('REMOTE_CLOCK_IN', 'Remote Clock-in'), ('WEEK_OFF_WORK', 'Week-Off Work'), ('OTHER', 'Other')], default='MISSED_PUNCH', max_length=20, verbose_name='Change Type'),
        ),
    ]
