# Generated by Django 4.2.27 on 2026-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_alter_regularizationrequest_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='travel_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
