# Generated by Django 4.2.27 on 2026-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0046_payslip_travel_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='tds_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
