# Generated by Django 4.2.27 on 2026-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0047_payslip_tds_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_rejoining',
            field=models.BooleanField(default=False, help_text='True if this employee is a rejoining ex-employee. Bypasses probation period check.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='original_joining_date',
            field=models.DateField(blank=True, help_text='The very first date this employee joined the organization (before any exit). Used to calculate total service tenure for rejoining employees.', null=True, verbose_name='Original Joining Date'),
        ),
    ]
