# Generated by Django 4.2.23 on 2026-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backup_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20)),
                ('enforce_2fa', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('module_employee_mgmt', models.BooleanField(default=True)),
                ('module_attendance', models.BooleanField(default=True)),
                ('module_payroll', models.BooleanField(default=True)),
                ('module_ai', models.BooleanField(default=True)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
