# Generated by Django 4.2.23 on 2026-02-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_biometricdevice'),
        ('core', '0005_globalconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('LEAVE', 'Leave Request'), ('ATTENDANCE', 'Attendance Regularization'), ('EXPENSE', 'Expense Claim'), ('ASSET', 'Asset Request')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('levels', models.PositiveIntegerField(default=1, help_text='Number of approval levels')),
                ('levels_config', models.JSONField(default=dict, help_text='e.g. {"1": {"role": "MANAGER"}, "2": {"role": "COMPANY_ADMIN"}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='companies.company')),
            ],
        ),
    ]
