# Generated by Django 4.2.23 on 2026-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_approvalworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_REQUEST', 'Leave Request'), ('REGULARIZATION_REQUEST', 'Regularization Request'), ('SHIFT_CHANGE', 'Shift Change')], max_length=30),
        ),
    ]
