# Generated by Django 4.2.27 on 2026-02-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_shift_change_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupConfiguration',
        ),
        migrations.RemoveField(
            model_name='backupjob',
            name='triggered_by_user',
        ),
        migrations.DeleteModel(
            name='BackupSnapshot',
        ),
        migrations.DeleteModel(
            name='BackupJob',
        ),
    ]
