# Generated by Django 4.2.27 on 2026-02-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_delete_backupconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_backup_enabled', models.BooleanField(default=True, help_text='Enable scheduled database backups')),
                ('database_backup_interval_hours', models.IntegerField(default=3, help_text='Hours between database backups')),
                ('media_backup_enabled', models.BooleanField(default=True, help_text='Enable scheduled media backups')),
                ('media_backup_hour', models.IntegerField(default=2, help_text='Hour of day (0-23) for daily media backup')),
                ('restore_test_enabled', models.BooleanField(default=True, help_text='Enable monthly restore testing')),
                ('restore_test_day', models.IntegerField(default=1, help_text='Day of month (1-28) for restore test')),
                ('keep_last', models.IntegerField(default=8, help_text='Keep the last N snapshots')),
                ('keep_daily', models.IntegerField(default=7, help_text='Keep daily snapshots for N days')),
                ('keep_weekly', models.IntegerField(default=4, help_text='Keep weekly snapshots for N weeks')),
                ('keep_monthly', models.IntegerField(default=12, help_text='Keep monthly snapshots for N months')),
                ('notify_on_success', models.BooleanField(default=True, help_text='Send notification on successful backup')),
                ('notify_on_failure', models.BooleanField(default=True, help_text='Send notification on failed backup')),
                ('repository_database', models.CharField(default='rclone:onedrive:HRMS-Backups/database', editable=False, max_length=255)),
                ('repository_media', models.CharField(default='rclone:onedrive:HRMS-Backups/media', editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
            },
        ),
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(help_text='Restic snapshot short ID', max_length=64, unique=True)),
                ('snapshot_type', models.CharField(choices=[('database', 'Database'), ('media', 'Media Files')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(help_text='When this snapshot was created')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('repository', models.CharField(default='rclone:onedrive:HRMS-Backups', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Restic tags for this snapshot')),
                ('retention_reason', models.CharField(blank=True, help_text='Why this snapshot is kept (latest, daily, weekly, monthly)', max_length=50)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='When this snapshot was last synced from restic')),
            ],
            options={
                'verbose_name': 'Backup Snapshot',
                'verbose_name_plural': 'Backup Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='Unique identifier for this backup job', max_length=64, unique=True)),
                ('job_type', models.CharField(choices=[('database', 'Database'), ('media', 'Media Files'), ('full', 'Full Backup'), ('restore_test', 'Restore Test')], db_index=True, default='database', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When this job was scheduled to run', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When this job started executing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this job finished (success or failure)', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('snapshot_id', models.CharField(blank=True, help_text='Restic snapshot ID if backup succeeded', max_length=64)),
                ('repository', models.CharField(default='rclone:onedrive:HRMS-Backups', help_text='Restic repository path', max_length=255)),
                ('encrypted', models.BooleanField(default=False, help_text='Whether this backup is encrypted')),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Size of backup in bytes', null=True)),
                ('files_count', models.IntegerField(blank=True, help_text='Number of files backed up', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed')),
                ('triggered_by', models.CharField(default='schedule', help_text='What triggered this backup (schedule, manual, deploy)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by_user', models.ForeignKey(blank=True, help_text='User who triggered manual backup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Job',
                'verbose_name_plural': 'Backup Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status'], name='core_backup_job_typ_017a36_idx'), models.Index(fields=['created_at'], name='core_backup_created_d1af47_idx'), models.Index(fields=['status', 'created_at'], name='core_backup_status_6dbb90_idx')],
            },
        ),
    ]
