# Generated by Django 4.2.23 on 2026-02-25 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0035_remove_activity_tracking_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_productive_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_unproductive_time', models.DurationField(default=datetime.timedelta(0))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_idle', models.BooleanField(default=False)),
                ('idle_duration_seconds', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='BrowserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('search_query', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_activities', to='employees.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browser_logs', to='activity_monitoring.activitysession')),
            ],
            options={
                'verbose_name_plural': 'Browser Activities',
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='activity_mo_employe_0be99d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('window_title', models.CharField(blank=True, max_length=500, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('duration', models.DurationField()),
                ('is_productive', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_activities', to='employees.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='activity_monitoring.activitysession')),
            ],
            options={
                'verbose_name_plural': 'App Activities',
                'indexes': [models.Index(fields=['employee', 'start_time'], name='activity_mo_employe_6aa2ca_idx'), models.Index(fields=['app_name'], name='activity_mo_app_nam_15cc14_idx')],
            },
        ),
    ]
