# Generated by Django 4.2.23 on 2026-02-26 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_remove_activity_tracking_enabled'),
        ('activity_monitoring', '0002_employeedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USB_INSERT', 'USB Device Inserted'), ('USB_REMOVE', 'USB Device Removed'), ('NETWORK_CHANGE', 'Network Connection Changed'), ('FILE_SYNC', 'Large File Operation Detected')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
