# Generated by Django 4.2.23 on 2026-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_monitoring', '0003_systemevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('USB_INSERT', 'USB Device Inserted'), ('USB_REMOVE', 'USB Device Removed'), ('NETWORK_CHANGE', 'Network Connection Changed'), ('FILE_SYNC', 'Large File Operation Detected'), ('FILE_TRANSFER', 'Security Alert: File Transfer')], max_length=50),
        ),
    ]
