# Generated by Django 4.2.27 on 2026-03-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_remove_activity_tracking_enabled'),
        ('activity_monitoring', '0004_alter_systemevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedevice',
            name='agent_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_screenshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='employees.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='activity_monitoring.activitysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
