"""
Django settings for hrms_core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import environ

# Initialize environment variables
env = environ.Env(
    # Set default values and casting
    DEBUG=(bool, False),
    CORS_ALLOW_ALL_ORIGINS=(bool, True),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
    POSTHOG_ENABLED=(bool, True),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "testserver"])

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    # Unfold admin theme (must be before django.contrib.admin)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.inlines",
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "widget_tweaks",
    "import_export",  # django-import-export
    "crispy_forms",
    "crispy_tailwind",
    "django_celery_beat",
    "django_celery_results",
    "hijack",
    "hijack.contrib.admin",
    # Local apps
    "companies",
    "accounts",
    "employees",
    "core.apps.CoreConfig",  # Changed to use AppConfig for signal handling
    "superadmin",
    "ai_assistant",  # AI-powered features
    "handbooks",  # Employee handbooks with location-based access
    "policies",  # Company Policies
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.CustomAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "hijack.middleware.HijackUserMiddleware",  # User impersonation
    "core.middleware.CompanyIsolationMiddleware",
    "core.middleware.LoggingMiddleware",  # Loguru request logging
    "hrms_core.posthog_config.PostHogMiddleware",  # PostHog error tracking
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hrms_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.notification_count",  # Notification count for admins/managers
            ],
        },
    },
]

WSGI_APPLICATION = "hrms_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration
DB_ENGINE = env("DB_ENGINE", default="django.db.backends.postgresql")

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
    }
}

# Add PostgreSQL-specific options only if using PostgreSQL
if "postgresql" in DB_ENGINE:
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "disable",
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = env("STATIC_URL", default="/static/")
STATIC_ROOT = env("STATIC_ROOT", default=BASE_DIR / "staticfiles")
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = env("MEDIA_ROOT", default=BASE_DIR / "media")

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

CORS_ALLOW_ALL_ORIGINS = env("CORS_ALLOW_ALL_ORIGINS")  # For development

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# Email Configuration for Birthday/Anniversary Notifications
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.office365.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_USE_SSL = env("EMAIL_USE_SSL")
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="HR <noreply@example.com>")
SERVER_EMAIL = env("SERVER_EMAIL", default="")

# PostHog Configuration for Error Tracking and Analytics
POSTHOG_API_KEY = env("POSTHOG_API_KEY", default="")
POSTHOG_HOST = env("POSTHOG_HOST", default="https://us.i.posthog.com")
POSTHOG_ENABLED = env("POSTHOG_ENABLED")

# Logging Configuration
LOG_LEVEL = env("LOG_LEVEL", default="DEBUG" if DEBUG else "INFO")
LOG_DIR = env("LOG_DIR", default=str(BASE_DIR / "_logs"))

# OpenAI Configuration
OPENAI_API_KEY = env("OPENAI_API_KEY", default=None)

# Initialize Loguru logging (only once)
from hrms_core.logging_config import initialize_logging, setup_django_logging

initialize_logging()
setup_django_logging()

# =============================================================================
# Crispy Forms Configuration (Tailwind for Unfold compatibility)
# =============================================================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# =============================================================================
# Celery Configuration (Redis broker, database-backed periodic tasks)
# =============================================================================
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/1")
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = "django-db"  # Store results in Django database
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# =============================================================================
# Unfold Admin Theme Configuration
# =============================================================================
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def environment_callback(request):
    """Return environment label for admin header."""
    if DEBUG:
        return ["Development", "warning"]
    return ["Production", "danger"]


def badge_callback(request):
    """Return notification count for dashboard badge."""
    return 0  # Implement actual count logic if needed


UNFOLD = {
    "SITE_TITLE": "HRMS PBS",
    "SITE_HEADER": "HRMS PBS",
    "SITE_SUBHEADER": "Human Resource Management System",
    "SITE_URL": "/",
    "SITE_SYMBOL": "corporate_fare",  # Material icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "ENVIRONMENT": "hrms_core.settings.environment_callback",
    "LOGIN": {
        "redirect_after": lambda _request: reverse_lazy("admin:index"),
    },
    "COLORS": {
        "primary": {
            "50": "oklch(97.7% .014 254.604)",
            "100": "oklch(93.2% .032 255.585)",
            "200": "oklch(86.2% .065 259.391)",
            "300": "oklch(75.8% .113 259.416)",
            "400": "oklch(64.6% .158 262.052)",
            "500": "oklch(54.6% .215 262.881)",
            "600": "oklch(48.8% .243 264.376)",
            "700": "oklch(44.4% .23 265.638)",
            "800": "oklch(38.3% .19 265.522)",
            "900": "oklch(33.2% .146 266.059)",
            "950": "oklch(23.5% .106 268.022)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Organization"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Companies"),
                        "icon": "business",
                        "link": reverse_lazy("admin:companies_company_changelist"),
                    },
                    {
                        "title": _("Locations"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:companies_location_changelist"),
                    },
                    {
                        "title": _("Shift Schedules"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:companies_shiftschedule_changelist"),
                    },
                    {
                        "title": _("Holidays"),
                        "icon": "celebration",
                        "link": reverse_lazy("admin:companies_holiday_changelist"),
                    },
                    {
                        "title": _("Announcements"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:companies_announcement_changelist"),
                    },
                ],
            },
            {
                "title": _("People"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Employees"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:employees_employee_changelist"),
                    },
                    {
                        "title": _("Emergency Contacts"),
                        "icon": "emergency",
                        "link": reverse_lazy("admin:employees_emergencycontact_changelist"),
                    },
                ],
            },
            {
                "title": _("Attendance"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Attendance Records"),
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:employees_attendance_changelist"),
                    },
                    {
                        "title": _("Attendance Sessions"),
                        "icon": "timer",
                        "link": reverse_lazy("admin:employees_attendancesession_changelist"),
                    },
                ],
            },
            {
                "title": _("Documents"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Handbook Sections"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:handbooks_handbooksection_changelist"),
                    },
                    {
                        "title": _("Handbooks"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:handbooks_handbook_changelist"),
                    },
                    {
                        "title": _("Acknowledgments"),
                        "icon": "verified",
                        "link": reverse_lazy("admin:handbooks_handbookacknowledgment_changelist"),
                    },
                ],
            },
            {
                "title": _("AI & Automation"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Attrition Risks"),
                        "icon": "trending_down",
                        "link": reverse_lazy("admin:ai_assistant_attritionrisk_changelist"),
                    },
                    {
                        "title": _("Resume Parsing Jobs"),
                        "icon": "description",
                        "link": reverse_lazy("admin:ai_assistant_resumeparsingjob_changelist"),
                    },
                ],
            },
            {
                "title": _("Scheduled Tasks"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Periodic Tasks"),
                        "icon": "event_repeat",
                        "link": reverse_lazy("admin:django_celery_beat_periodictask_changelist"),
                    },
                    {
                        "title": _("Crontab Schedules"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:django_celery_beat_crontabschedule_changelist"),
                    },
                    {
                        "title": _("Interval Schedules"),
                        "icon": "timelapse",
                        "link": reverse_lazy("admin:django_celery_beat_intervalschedule_changelist"),
                    },
                ],
            },
        ],
    },
}
