# Generated by Django 4.2.27 on 2026-01-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]
