# Generated by Django 4.2.23 on 2026-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_finance_manager',
            field=models.BooleanField(default=False),
        ),
    ]
