# Generated by Django 4.2.27 on 2026-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('EMPLOYEE_MANAGER', 'HR'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('TECH_SUPPORT', 'Tech Support')], default='EMPLOYEE', max_length=50),
        ),
    ]
