# Generated by Django 4.2.23 on 2025-12-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0025_remove_employee_probation_completion_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeParsingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "parsed_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parsed_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parsed_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parsed_skills", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttritionRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0, help_text="Calculated risk score (0-100)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=dict, help_text="Factors contributing to risk score"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attrition_risk",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
