# Generated by Django 4.2.27 on 2026-01-12 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttritionRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0, help_text="Calculated risk score (0-100)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=dict, help_text="Factors contributing to risk score"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attrition_risk",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeParsingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "parsed_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parsed_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parsed_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parsed_skills", models.TextField(blank=True, null=True)),
                (
                    "candidate_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("domain", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "duplicate_check_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.resumeparsingjob",
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("parsed_certifications", models.JSONField(blank=True, null=True)),
                ("parsed_education", models.JSONField(blank=True, null=True)),
                ("parsed_experience", models.JSONField(blank=True, null=True)),
                ("parsed_github", models.URLField(blank=True, null=True)),
                ("parsed_linkedin", models.URLField(blank=True, null=True)),
                (
                    "parsed_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("parsed_portfolio", models.URLField(blank=True, null=True)),
                ("parsed_projects", models.JSONField(blank=True, null=True)),
                ("parsed_skills_json", models.JSONField(blank=True, null=True)),
                ("role_fit", models.CharField(blank=True, max_length=100, null=True)),
                ("total_experience_years", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("bot_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
