# Generated by Django 4.2.23 on 2026-01-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeparsingjob",
            name="candidate_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="duplicate_check_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_assistant.resumeparsingjob",
            ),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_certifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_education",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_experience",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_portfolio",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_projects",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="parsed_skills_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="role_fit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resumeparsingjob",
            name="total_experience_years",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
