# Generated by Django 4.2.27 on 2026-01-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_fix_locationlog_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0014_alter_company_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='Main handbook content (supports HTML/rich text)')),
                ('version', models.CharField(default='1.0', help_text='Version number of this handbook', max_length=50)),
                ('is_published', models.BooleanField(default=False, help_text='Only published handbooks are visible to employees')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this handbook becomes effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_acknowledgment', models.BooleanField(default=False, help_text='Employees must acknowledge reading this handbook')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbooks', to='companies.company')),
                ('created_by', models.ForeignKey(help_text='Admin who created this handbook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbooks_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Location/Entity this handbook belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='handbooks', to='companies.location')),
            ],
            options={
                'verbose_name': 'Handbook',
                'verbose_name_plural': 'Handbooks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HandbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class (e.g., 📘, 🎯, 📋)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_sections', to='companies.company')),
            ],
            options={
                'verbose_name': 'Handbook Section',
                'verbose_name_plural': 'Handbook Sections',
                'ordering': ['order', 'title'],
                'unique_together': {('company', 'title')},
            },
        ),
        migrations.CreateModel(
            name='HandbookAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Upload PDF, images, or other documents', upload_to='handbook_attachments/%Y/%m/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='handbooks.handbook')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handbook Attachment',
                'verbose_name_plural': 'Handbook Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='handbook',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section this content belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbook_entries', to='handbooks.handbooksection'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='updated_by',
            field=models.ForeignKey(help_text='Admin who last updated this handbook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbooks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HandbookAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_acknowledgments', to='employees.employee')),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='handbooks.handbook')),
            ],
            options={
                'verbose_name': 'Handbook Acknowledgment',
                'verbose_name_plural': 'Handbook Acknowledgments',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('handbook', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='handbook',
            index=models.Index(fields=['company', 'location'], name='handbooks_h_company_818cba_idx'),
        ),
        migrations.AddIndex(
            model_name='handbook',
            index=models.Index(fields=['is_published', 'effective_date'], name='handbooks_h_is_publ_b33768_idx'),
        ),
    ]
