# Generated by Django 4.2.27 on 2026-01-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company name (e.g., Petabytz)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "allowed_domains",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of allowed domains (e.g., petabytz.com,www.petabytz.com)",
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "db_schema",
                    models.CharField(
                        blank=True,
                        help_text="Database schema name for this company",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email_domain",
                    models.CharField(
                        default="example.com",
                        help_text="Email domain for employees (e.g., petabytz.com for user@petabytz.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("INDIA", "India"),
                            ("DHAKA", "Dhaka, Bangladesh"),
                            ("BOTH", "India & Dhaka"),
                        ],
                        default="INDIA",
                        help_text="Primary location of the company",
                        max_length=20,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "primary_domain",
                    models.CharField(
                        default="example.com",
                        help_text="Primary domain (e.g., petabytz.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name (e.g., Diwali, Independence Day)",
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(help_text="Holiday date")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("INDIA", "India"),
                            ("US", "United States"),
                            ("DHAKA", "Dhaka, Bangladesh"),
                            ("UK", "United Kingdom"),
                            ("GLOBAL", "Global (All Locations)"),
                        ],
                        default="GLOBAL",
                        help_text="Location where this holiday applies",
                        max_length=20,
                    ),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory Holiday"),
                            ("OPTIONAL", "Optional Holiday"),
                            ("RESTRICTED", "Restricted Holiday"),
                        ],
                        default="MANDATORY",
                        help_text="Type of holiday",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the holiday",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this holiday is currently active",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of the holiday")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Admin who created this",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["company", "year"],
                        name="companies_h_company_5715bf_idx",
                    ),
                    models.Index(
                        fields=["company", "location"],
                        name="companies_h_company_f6931c_idx",
                    ),
                    models.Index(fields=["date"], name="companies_h_date_caf000_idx"),
                ],
                "unique_together": {("company", "name", "date", "location")},
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["primary_domain"], name="companies_c_primary_28ea07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["email_domain"], name="companies_c_email_d_bd4ed1_idx"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(
                choices=[
                    ("INDIA", "India"),
                    ("US", "United States"),
                    ("BOTH", "India & Dhaka"),
                ],
                default="INDIA",
                help_text="Primary location of the company",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShiftTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.CharField(default="9:00 hrs", max_length=100)),
                (
                    "morning_break",
                    models.CharField(
                        default="15mins from 10:45 to 11:00", max_length=255
                    ),
                ),
                (
                    "lunch_break",
                    models.CharField(default="45min from 1:00 to 1:45", max_length=255),
                ),
                (
                    "evening_break",
                    models.CharField(
                        default="15mins from 4:00 to 4:30", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_timing",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Morning Shift, Night Shift, General",
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "grace_period_minutes",
                    models.IntegerField(
                        default=15, help_text="Grace period in minutes for late arrival"
                    ),
                ),
                (
                    "early_departure_threshold_minutes",
                    models.IntegerField(
                        default=15,
                        help_text="Minutes before shift end considered early departure",
                    ),
                ),
                (
                    "lunch_break_start",
                    models.TimeField(
                        blank=True, help_text="Lunch break start time", null=True
                    ),
                ),
                (
                    "lunch_break_end",
                    models.TimeField(
                        blank=True, help_text="Lunch break end time", null=True
                    ),
                ),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AlterField(
            model_name="holiday",
            name="location",
            field=models.CharField(
                default="GLOBAL",
                help_text="Location where this holiday applies",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., India, US - East, Dhaka)",
                        max_length=255,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO Country Code (e.g., IN, US, BD)", max_length=5
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Kolkata",
                        help_text="Timezone for this location",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "name")},
            },
        ),
        migrations.RenameIndex(
            model_name="holiday",
            new_name="companies_h_company_a18c66_idx",
            old_name="companies_h_company_f6931c_idx",
        ),
        migrations.AlterField(
            model_name="holiday",
            name="location",
            field=models.ForeignKey(
                help_text="Location where this holiday applies",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="companies.location",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="companies.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific location for this announcement. Leave empty for all locations.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="companies.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="shiftschedule",
            name="allowed_late_logins",
            field=models.IntegerField(
                default=5,
                help_text="Number of allowed late logins per month before reaction",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedule",
            name="grace_exceeded_action",
            field=models.CharField(
                choices=[
                    ("HALF_DAY", "Mark as Half Day"),
                    ("LOP", "Loss of Pay (Full Day)"),
                    ("NONE", "No Action (Just Track)"),
                ],
                default="HALF_DAY",
                help_text="Action to take when allowed late logins count is exceeded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shiftschedule",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning Shift"),
                    ("AFTERNOON", "Afternoon Shift"),
                    ("NIGHT", "Night Shift"),
                ],
                default="MORNING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShiftBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Lunch Break, Tea Break", max_length=100
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="companies.shiftschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(
                default="INR",
                help_text="Currency symbol (e.g., INR, USD)",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="LocationWeekOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=True)),
                ("sunday", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_week_offs",
                        to="companies.company",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_off_config",
                        to="companies.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="hr_email",
            field=models.EmailField(
                blank=True,
                help_text="HR email address for sending birthday/anniversary emails",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="hr_email_name",
            field=models.CharField(
                blank=True,
                default="HR Team",
                help_text="Display name for HR emails (e.g., 'Petabytz HR')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="hr_email_password",
            field=models.CharField(
                blank=True,
                help_text="Email password or app password (encrypted in production)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="companies.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designations",
                        to="companies.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
    ]
