# Generated by Django 4.2.23 on 2025-12-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name (e.g., Diwali, Independence Day)",
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(help_text="Holiday date")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("INDIA", "India"),
                            ("US", "United States"),
                            ("DHAKA", "Dhaka, Bangladesh"),
                            ("UK", "United Kingdom"),
                            ("GLOBAL", "Global (All Locations)"),
                        ],
                        default="GLOBAL",
                        help_text="Location where this holiday applies",
                        max_length=20,
                    ),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory Holiday"),
                            ("OPTIONAL", "Optional Holiday"),
                            ("RESTRICTED", "Restricted Holiday"),
                        ],
                        default="MANDATORY",
                        help_text="Type of holiday",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the holiday",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this holiday is currently active",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of the holiday")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Admin who created this",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["company", "year"],
                        name="companies_h_company_5715bf_idx",
                    ),
                    models.Index(
                        fields=["company", "location"],
                        name="companies_h_company_f6931c_idx",
                    ),
                    models.Index(fields=["date"], name="companies_h_date_caf000_idx"),
                ],
                "unique_together": {("company", "name", "date", "location")},
            },
        ),
    ]
