# Generated by Django 4.2.23 on 2025-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_holiday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="domain",
        ),
        migrations.AddField(
            model_name="company",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="allowed_domains",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of allowed domains (e.g., petabytz.com,www.petabytz.com)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="db_schema",
            field=models.CharField(
                blank=True,
                help_text="Database schema name for this company",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="email_domain",
            field=models.CharField(
                default="example.com",
                help_text="Email domain for employees (e.g., petabytz.com for user@petabytz.com)",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(
                choices=[
                    ("INDIA", "India"),
                    ("DHAKA", "Dhaka, Bangladesh"),
                    ("BOTH", "India & Dhaka"),
                ],
                default="INDIA",
                help_text="Primary location of the company",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_domain",
            field=models.CharField(
                default="example.com",
                help_text="Primary domain (e.g., petabytz.com)",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Company name (e.g., Petabytz)", max_length=255, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["primary_domain"], name="companies_c_primary_28ea07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["email_domain"], name="companies_c_email_d_bd4ed1_idx"
            ),
        ),
    ]
