# Generated by Django 4.2.23 on 2025-12-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_remove_company_domain_company_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(
                choices=[
                    ("INDIA", "India"),
                    ("US", "United States"),
                    ("BOTH", "India & Dhaka"),
                ],
                default="INDIA",
                help_text="Primary location of the company",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShiftTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.CharField(default="9:00 hrs", max_length=100)),
                (
                    "morning_break",
                    models.CharField(
                        default="15mins from 10:45 to 11:00", max_length=255
                    ),
                ),
                (
                    "lunch_break",
                    models.CharField(default="45min from 1:00 to 1:45", max_length=255),
                ),
                (
                    "evening_break",
                    models.CharField(
                        default="15mins from 4:00 to 4:30", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_timing",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
