# Generated by Django 4.2.23 on 2025-12-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_company_location_shifttiming"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Morning Shift, Night Shift, General",
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "grace_period_minutes",
                    models.IntegerField(
                        default=15, help_text="Grace period in minutes for late arrival"
                    ),
                ),
                (
                    "early_departure_threshold_minutes",
                    models.IntegerField(
                        default=15,
                        help_text="Minutes before shift end considered early departure",
                    ),
                ),
                (
                    "lunch_break_start",
                    models.TimeField(
                        blank=True, help_text="Lunch break start time", null=True
                    ),
                ),
                (
                    "lunch_break_end",
                    models.TimeField(
                        blank=True, help_text="Lunch break end time", null=True
                    ),
                ),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
    ]
