# Generated by Django 4.2.23 on 2025-12-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_shiftschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="location",
            field=models.CharField(
                default="GLOBAL",
                help_text="Location where this holiday applies",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., India, US - East, Dhaka)",
                        max_length=255,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO Country Code (e.g., IN, US, BD)", max_length=5
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Kolkata",
                        help_text="Timezone for this location",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "name")},
            },
        ),
    ]
