# Generated by Django 4.2.23 on 2025-12-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_holiday_location_location"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="holiday",
            new_name="companies_h_company_a18c66_idx",
            old_name="companies_h_company_f6931c_idx",
        ),
        migrations.AlterField(
            model_name="holiday",
            name="location",
            field=models.ForeignKey(
                help_text="Location where this holiday applies",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="companies.location",
            ),
        ),
    ]
