# Generated by Django 4.2.23 on 2025-12-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftschedule",
            name="allowed_late_logins",
            field=models.IntegerField(
                default=5,
                help_text="Number of allowed late logins per month before reaction",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedule",
            name="grace_exceeded_action",
            field=models.CharField(
                choices=[
                    ("HALF_DAY", "Mark as Half Day"),
                    ("LOP", "Loss of Pay (Full Day)"),
                    ("NONE", "No Action (Just Track)"),
                ],
                default="HALF_DAY",
                help_text="Action to take when allowed late logins count is exceeded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shiftschedule",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning Shift"),
                    ("AFTERNOON", "Afternoon Shift"),
                    ("NIGHT", "Night Shift"),
                ],
                default="MORNING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShiftBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Lunch Break, Tea Break", max_length=100
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="companies.shiftschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
