# Generated by Django 4.2.23 on 2025-12-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_shiftschedule_allowed_late_logins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(
                default="INR",
                help_text="Currency symbol (e.g., INR, USD)",
                max_length=10,
            ),
        ),
    ]
