# Generated by Django 4.2.23 on 2025-12-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_locationweekoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="hr_email",
            field=models.EmailField(
                blank=True,
                help_text="HR email address for sending birthday/anniversary emails",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="hr_email_name",
            field=models.CharField(
                blank=True,
                default="HR Team",
                help_text="Display name for HR emails (e.g., 'Petabytz HR')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="hr_email_password",
            field=models.CharField(
                blank=True,
                help_text="Email password or app password (encrypted in production)",
                max_length=255,
                null=True,
            ),
        ),
    ]
