# Generated by Django 4.2.27 on 2026-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email_domain",
            field=models.CharField(
                help_text="Email domain for employees (e.g., petabytz.com for user@petabytz.com)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="primary_domain",
            field=models.CharField(
                help_text="Primary domain (e.g., petabytz.com)",
                max_length=255,
                unique=True,
            ),
        ),
    ]
