# Generated by Django 4.2.23 on 2026-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency symbol for this location (e.g., INR, USD)', max_length=10),
        ),
    ]
