# Generated by Django 4.2.23 on 2026-02-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_explicitly_name_holiday_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_employer_rate', models.DecimalField(decimal_places=2, default=13.0, help_text='Employer PF %', max_digits=5)),
                ('pf_employee_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Employee PF %', max_digits=5)),
                ('pf_ceiling', models.DecimalField(decimal_places=2, default=15000.0, help_text='PF Wage Ceiling', max_digits=12)),
                ('esi_employer_rate', models.DecimalField(decimal_places=2, default=3.25, help_text='Employer ESI %', max_digits=5)),
                ('esi_employee_rate', models.DecimalField(decimal_places=2, default=0.75, help_text='Employee ESI %', max_digits=5)),
                ('esi_ceiling', models.DecimalField(decimal_places=2, default=21000.0, help_text='ESI Wage Ceiling', max_digits=12)),
                ('pt_threshold', models.DecimalField(decimal_places=2, default=20000.0, max_digits=12)),
                ('pt_amount_below', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('pt_amount_above', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('hra_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('lta_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('special_allowance_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('bd_basic_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('bd_hra_percentage', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('bd_medical_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('bd_conveyance_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('us_basic_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('us_tax_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='companies.company')),
            ],
        ),
    ]
