# Generated by Django 4.2.23 on 2026-02-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_payrollconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Door, Reception, Server Room', max_length=100)),
                ('device_type', models.CharField(choices=[('ZKTECO', 'ZKTeco / ESSL'), ('ANVIZ', 'Anviz'), ('MATRIX', 'Matrix COSEC'), ('HIKVISION', 'Hikvision'), ('SUPREMA', 'Suprema')], default='ZKTECO', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='LAN IP of the device')),
                ('port', models.IntegerField(default=4370)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.location')),
            ],
        ),
    ]
