# Generated by Django 4.2.27 on 2026-02-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_biometricdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holiday',
            new_name='companies_h_company_5715bf_idx',
            old_name='holiday_company_year_idx',
        ),
        migrations.RenameIndex(
            model_name='holiday',
            new_name='companies_h_date_caf000_idx',
            old_name='holiday_date_idx',
        ),
    ]
