# Generated by Django 4.2.23 on 2026-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_rename_companies_h_company_5715bf_idx_holiday_company_year_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='Allow flexible clock-in/out without late/early penalties'),
        ),
    ]
