# Generated by Django 4.2.23 on 2026-02-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_shiftschedule_is_flexible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Email domain (e.g., petabytz.com, example.org)', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary domain for the company')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this domain', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Admin who added this domain', max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='companies.company')),
            ],
            options={
                'verbose_name': 'Email Domain',
                'verbose_name_plural': 'Email Domains',
                'ordering': ['-is_primary', 'domain'],
                'unique_together': {('company', 'domain')},
            },
        ),
    ]
