# Generated by Django 4.2.23 on 2026-03-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollbatch',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='FinanceAuditLog',
        ),
        migrations.DeleteModel(
            name='PayrollBatch',
        ),
    ]
