# Generated by Django 4.2.27 on 2026-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0004_bankaccount_bankstatement_purchaserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresult',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
