# Generated by Django 4.2.27 on 2026-07-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_portal', '0005_reconciliationresult_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit (Expense)'), ('credit', 'Credit (Deposit)')], default='debit', max_length=10),
        ),
    ]
